### ISSUE TITLE
Wiki 일반사항 오타 수정

### ISSUE THREAD

**Issue by bestseob93** [GiGAGenie-ServiceSDK/UserGuide#1]
# 일반사항
## 링크, 소스 태그의 경로 설정 방법
상대적 경로인 곳에 
`<link href=”/css/style.css” rel=”stylesheet”>`
`<script src=”/js/jquery-min.js”></script>`
절대 경로 삽입되어 있습니다.

**Comment by Heewon123** [comment]
내용 수정했습니다. 감사합니다. :)
